### ISSUE TITLE
Cannot set property navigator of #<Object> which has only a getter

### ISSUE THREAD

**Issue by tombeteende** [ljacobsson/cfn-diagram#237]
I'm running `cfn-dia` locally (even help) and getting the following error - 

os - Mac OS
node version - Node.js v21.1.0

```
/opt/homebrew/lib/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:25
global.navigator = window.navigator;
                 ^

TypeError: Cannot set property navigator of #<Object> which has only a getter
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:25:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/@mhlabs/cfn-diagram/commands/draw.io/index.js:2:21)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```

**Comment by V4G4X** [comment]
bump

**Comment by ljacobsson** [comment]
Sorry for the delay from my end. Been through a busy period at work, but this should now be fixed as of v1.1.39

**Comment by tombeteende** [comment]
Thank you, will check, hope you are better bow
